package com.doctalk.app.presentation.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val md_theme_light_primary = Color(0xFF0061a4)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFd0e4ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001d36)
val md_theme_light_secondary = Color(0xFF535e70)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFd7e3f7)
val md_theme_light_onSecondaryContainer = Color(0xFF101c2b)
val md_theme_light_tertiary = Color(0xFF6b5778)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFf2daff)
val md_theme_light_onTertiaryContainer = Color(0xFF251432)
val md_theme_light_error = Color(0xFFba1a1a)
val md_theme_light_errorContainer = Color(0xFFffdad6)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFfffbfe)
val md_theme_light_onBackground = Color(0xFF1a1b1e)
val md_theme_light_surface = Color(0xFFfffbfe)
val md_theme_light_onSurface = Color(0xFF1a1b1e)
val md_theme_light_surfaceVariant = Color(0xFFdde2ea)
val md_theme_light_onSurfaceVariant = Color(0xFF41474d)
val md_theme_light_outline = Color(0xFF71787e)
val md_theme_light_inverseOnSurface = Color(0xFFf1f0f4)
val md_theme_light_inverseSurface = Color(0xFF2f3033)
val md_theme_light_inversePrimary = Color(0xFFa0cafd)

// Dark theme colors
val md_theme_dark_primary = Color(0xFFa0cafd)
val md_theme_dark_onPrimary = Color(0xFF003258)
val md_theme_dark_primaryContainer = Color(0xFF00497d)
val md_theme_dark_onPrimaryContainer = Color(0xFFd0e4ff)
val md_theme_dark_secondary = Color(0xFFbbc7db)
val md_theme_dark_onSecondary = Color(0xFF253140)
val md_theme_dark_secondaryContainer = Color(0xFF3b4858)
val md_theme_dark_onSecondaryContainer = Color(0xFFd7e3f7)
val md_theme_dark_tertiary = Color(0xFFd6bfdf)
val md_theme_dark_onTertiary = Color(0xFF3a2948)
val md_theme_dark_tertiaryContainer = Color(0xFF523f5f)
val md_theme_dark_onTertiaryContainer = Color(0xFFf2daff)
val md_theme_dark_error = Color(0xFFffb4ab)
val md_theme_dark_errorContainer = Color(0xFF93000a)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFffdad6)
val md_theme_dark_background = Color(0xFF1a1b1e)
val md_theme_dark_onBackground = Color(0xFFe3e2e6)
val md_theme_dark_surface = Color(0xFF1a1b1e)
val md_theme_dark_onSurface = Color(0xFFe3e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF41474d)
val md_theme_dark_onSurfaceVariant = Color(0xFFc1c7ce)
val md_theme_dark_outline = Color(0xFF8b9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe3e2e6)
val md_theme_dark_inversePrimary = Color(0xFF0061a4)

// Additional colors for specific use cases
val DocTalkBlue = Color(0xFF0061a4)
val DocTalkLightBlue = Color(0xFFa0cafd)
val DocTalkGray = Color(0xFF535e70)
val DocTalkLightGray = Color(0xFFdde2ea)
val DocTalkSuccess = Color(0xFF4caf50)
val DocTalkWarning = Color(0xFFff9800)
val DocTalkError = Color(0xFFf44336)
